version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:  

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 3s
      timeout: 3s
      retries: 5
  backend:
    image: iishimskij/foodgram_backend
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media 
  frontend:
    image: iishimskij/foodgram_frontend  
    env_file: .env
    volumes:
      - static_volume:/app/result_build/build
  nginx:
    image: nginx:1.19.3
    env_file: .env    
    depends_on:
      - backend    
    ports:
      - "5050:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - media_volume:/usr/share/nginx/html/media/      
